argo-cd:
  dex:
    enabled: false
  controller:
    args:
      appResyncPeriod: 90
  server:
    ingress:
      # -- Enable an ingress resource for the Argo CD server
      enabled: false
      # -- Additional ingress annotations
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-production
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      # -- Additional ingress labels
      labels: {}
      # -- Defines which ingress controller will implement the resource
      ingressClassName: "nginx"

      tls:
        - hosts:
          - argocd.somedomain.com
          secretName: argocd-somedomain-com

      # -- List of ingress hosts
      ## Argo Ingress.
      ## Hostnames must be provided if Ingress is enabled.
      ## Secrets must be manually created in the namespace
      hosts:
        - argocd.somedomain.com
    config:
      url: https://argo.somedomain.com
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm

repos:
  # - name:
  #   data:
  #     name: 
  #     project: 
  #     sshPrivateKey: 
  #     type: 
  #     url: 
